apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: my-test-function
  namespace: srvls-test
spec:
  runtime: nodejs18
  source:
    inline:
      dependencies: |
        {
          "name": "hellowithdeps",
          "version": "0.0.1",
          "dependencies": {
            "end-of-stream": "^1.4.1",
            "from2": "^2.3.0",
            "lodash": "^4.17.5"
          }
        }
      source: |
        module.exports = {
          main: function(event, context) {
            const name = process.env.PERSON_NAME;
            return 'Hello ' + name;
          }
        }
  env:
    - name: PERSON_NAME
      value: "John"